apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::048146544023:role/eksctl-eksctl-demo-nodegroup-ng-d-NodeInstanceRole-1ELP9XQKGYUQL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::048146544023:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-12T11:36:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1675"
  uid: 19ed7892-462d-4a1f-a065-913f2f20de10
